# Generated by Django 3.1.5 on 2021-05-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('math', models.CharField(max_length=50)),
                ('physic', models.CharField(max_length=50)),
                ('chemistry', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('precent', models.CharField(max_length=50)),
            ],
        ),
    ]
